### PR TITLE
FFI documentation in the guide

### PR DESCRIPTION
**Pull request by blamario**

### CODE REVIEW

**Comment by blamario** [comment]
Merging the guide commits from master is non-trivial, this PR will need to wait until staging is merged into master.

**Comment by L-as** [comment]
@blamario #391

**Review by TotallyNotChase — APPROVED** [review]
This is very nice. Out of curiosity since I haven't looked at the FFI code deeply yet, do users need to ensure their types' `Lift` instance corresponds correctly with their Plutarch type (in their Plutarch function(s)) in order for the `applyCode` their to work correctly? If so, it's potentially worth acknowledging in the guide,

**Comment by blamario** [comment]
Good point. I'll add some explanation.

**Comment by blamario** [comment]
> do users need to ensure their types' `Lift` instance corresponds correctly with their Plutarch type (in their Plutarch function(s)) in order for the `applyCode` their to work correctly?

No, FFI is orthogonal to `Lift`.

**Comment by blamario** [comment]
I added a deeper explanation of type correspondences.

**Review by TotallyNotChase — APPROVED** [review]

**Pull request merged**
