### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by L-as**

### CODE REVIEW

**Comment by L-as** [comment]
Given the existence of https://github.com/input-output-hk/plutus/tree/release/1.0.0, it might seem reasonable to switch to it, but unfortunately it doesn't support `serialiseData` AFAICT.

**Comment by L-as** [comment]
[secp256k1-haskell.log](https://github.com/Plutonomicon/plutarch/files/8502607/secp256k1-haskell.log)

No idea why this shit is failing

**Comment by L-as** [comment]
@srid there's some funky hspec stuff going on, I suspect because the behavior of the upstream functions changed slightly from what you expected.

**Comment by srid** [comment]
@L-as You can cherry-pick this commit: https://github.com/Plutonomicon/plutarch/commit/53ffb5e880b8530dd47ce4e8f8e773317cc67baf

By the way, it looks like updating dependencies seems to have improved the performance in some cases, while making it worse off in others.

**Comment by L-as** [comment]
@Synthetica9 will take a look at the Nix issues

**Comment by Synthetica9** [comment]
@L-as what are you trying to do in that last commit? I think you _meant_ the following:

```nix
diff --git a/flake.nix b/flake.nix
index 7774fd7..d36110b 100644
--- a/flake.nix
+++ b/flake.nix
@@ -149,73 +149,6 @@
               config.hsPkgs.hspec-discover
             ];
           };
-          extraSources = [
-            {
-              src = inputs.protolude;
-              subdirs = [ "." ];
-            }
-            {
-              src = inputs.cardano-prelude;
-              subdirs = [
-                "cardano-prelude"
-              ];
-            }
-            {
-              src = inputs.cardano-crypto;
-              subdirs = [ "." ];
-            }
-            {
-              src = inputs.flat;
-              subdirs = [ "." ];
-            }
-            {
-              src = inputs.cardano-base;
-              subdirs = [
-                "binary"
-                "cardano-crypto-class"
-              ];
-            }
-            {
-              src = inputs.sized-functors;
-              subdirs = [ "." ];
-            }
-            {
-              src = inputs.plutus;
-              subdirs = [
-                "plutus-core"
-                "plutus-ledger-api"
-                "plutus-tx"
-                "prettyprinter-configurable"
-                "word-array"
-              ];
-            }
-            {
-              src = inputs.hspec;
-              subdirs = [
-                "."
-                "hspec-core"
-                "hspec-contrib"
-                "hspec-discover"
-              ];
-            }
-            {
-              src = inputs.hspec-hedgehog;
-              subdirs = [ "." ];
-            }
-            {
-              src = inputs.hspec-golden;
-              subdirs = [ "." ];
-            }
-            {
-              src = inputs.secp256k1-haskell;
-              subdirs = [ "." ];
-            }
-            {
-              src = inputs.inline-r;
-              subdirs = [ "inline-r" ];
-            }
-          ];
-          # FIXME: Add shrinker if on GHC 8.10.7
         })
       ];
 
@@ -420,6 +353,75 @@
         let pkgSet = (nixpkgsFor system).haskell-nix.cabalProject' ({
           src = ./.;
           compiler-nix-name = ghcName;
+          extraSources = [
+            {
+              src = inputs.protolude;
+              subdirs = [ "." ];
+            }
+            {
+              src = inputs.cardano-prelude;
+              subdirs = [
+                "cardano-prelude"
+              ];
+            }
+            {
+              src = inputs.cardano-crypto;
+              subdirs = [ "." ];
+            }
+            {
+              src = inputs.flat;
+              subdirs = [ "." ];
+            }
+            {
+              src = inputs.cardano-base;
+              subdirs = [
+                "binary"
+                "cardano-crypto-class"
+              ];
+            }
+            {
+              src = inputs.sized-functors;
+              subdirs = [ "." ];
+            }
+            {
+              src = inputs.plutus;
+              subdirs = [
+                "plutus-core"
+                "plutus-ledger-api"
+                "plutus-tx"
+                "prettyprinter-configurable"
+                "word-array"
+              ];
+            }
+            {
+              src = inputs.hspec;
+              subdirs = [
+                "."
+                "hspec-core"
+                "hspec-contrib"
+                "hspec-discover"
+              ];
+            }
+            {
+              src = inputs.hspec-hedgehog;
+              subdirs = [ "." ];
+            }
+            {
+              src = inputs.hspec-golden;
+              subdirs = [ "." ];
+            }
+            {
+              src = inputs.secp256k1-haskell;
+              subdirs = [ "." ];
+            }
+            {
+              src = inputs.inline-r;
+              subdirs = [ "inline-r" ];
+            }
+          ] ++ (with inputs.nixpkgs.lib; optional (versionOlder ghcName "9") {
+            src = inputs.Shrinker;
+            subdirs = [ "." ];
+          });
           modules = haskellModules ++ [
             {
               packages.plutarch-test.flags.development = flagDevelopment;
```

**Comment by L-as** [comment]
Nope @Synthetica9 it has to be in the `haskellModules`, downstream users of Plutarch also use this module.

**Comment by L-as** [comment]
https://github.com/mlabs-haskell/haskell.nix/commit/4bf01c1d0b2281e5f6dc0069e8fa447f498b9962 fixes this issue, however I'm not sure this is the right solution (not to mention the implementation is very hacky)

**Comment by L-as** [comment]
Seems to mostly work! Fantastic! I'll probably merge tomorrow or today once I've fixed the final issues (fourmolu and HLS).

**Comment by L-as** [comment]
Merging as this is pretty important

**Pull request merged**
