### PR TITLE
Start plutarch extra

### PR DESCRIPTION
**Pull request by Geometer1729**

### CODE REVIEW

**Comment by TotallyNotChase** [comment]
ok so we definitely need to split this up. this PR should just contain the bare scaffold for plutarch-extra (as discussed). The utilities should follow steadily.

Also, the *fundamental* `PMap` (and `PValue`) should be in the main Plutarch library itself.

**Comment by L-as** [comment]
Why does this have so many irrelevant commits?

**Comment by Geometer1729** [comment]
> Why does this have so many irrelevant commits?

I based it on top of the list utils upstream branch because they have significant overlap.

**Comment by L-as** [comment]
Please don't include anything but the *scaffold* for `plutus-extra`.

**Comment by L-as** [comment]
i.e. the cabal files

**Comment by MangoIV** [comment]
I've moved this to #351 and the list upstream part to #357

**Pull request closed without merging**
