### PR TITLE
Plutarch Natural (basic sketch)

### PR DESCRIPTION
**Pull request by sergesku**
This is the starting point for implementing numerical stuff on top of Plutarch.

I'm not sure if we need to import the `plutus-numeric` modules to implement numeric classes such as `AdditiveHemigroup`, `IntegralDomain` etc.

### CODE REVIEW

**Comment by L-as** [comment]
We definitely don't want to depend on `plutus-numeric`.

**Comment by L-as** [comment]
Do we want a `plutarch-extra` now @kozross or what do you think?

**Comment by kozross** [comment]
We could, but I'd rather fractionate into multiple separate libraries, rather than a megarepo with sublibraries.

**Comment by L-as** [comment]
#139

**Comment by sergesku** [comment]
This stuff will be combined with the new Numeric library

**Pull request closed without merging**
