### PR TITLE
Add ci.nix

### PR DESCRIPTION
**Pull request by L-as**

### CODE REVIEW

**Comment by L-as** [comment]
@nixinator @MatthewCroughan I don't think the cache is set up. This evaluation is taking ages. It's probably building GHC.

**Comment by MatthewCroughan** [comment]
> @nixinator @MatthewCroughan I don't think the cache is set up. This evaluation is taking ages. It's probably building GHC.

Should we rely on IOHK cache? I'd like to know if things build from source or not. If it fails, that's more interesting. Once cached on our cachix, we won't need IOHK anyway.

**Comment by L-as** [comment]
That is true, let's leave this then and see what happens.

**Comment by L-as** [comment]
It finished!

**Comment by nixinator** [comment]
@L-as the runners not pulling from cachix, so it's rebuild, investigating so bear with me

**Pull request merged**
