### PR TITLE
GHC 9.2.1 support

### PR DESCRIPTION
**Pull request by L-as**

### CODE REVIEW

**Comment by L-as** [comment]
Current error:
```
plutus-core-lib-plutus-core> plutus-core/src/Data/Aeson/THReader.hs:14:22: error:
plutus-core-lib-plutus-core>     • Couldn't match type ‘Code m0’ with ‘Q’
plutus-core-lib-plutus-core>       Expected: Q (TExp a)
plutus-core-lib-plutus-core>         Actual: Code m0 (TExp a)
plutus-core-lib-plutus-core>     • In the Template Haskell quotation [|| res ||]
plutus-core-lib-plutus-core>       In the expression: [|| res ||]
plutus-core-lib-plutus-core>       In a case alternative: Right res -> [|| res ||]
plutus-core-lib-plutus-core>    |
plutus-core-lib-plutus-core> 14 |         Right res -> [||res||]
plutus-core-lib-plutus-core>    |                      ^^^^^^^^^
plutus-core-lib-plutus-core> [  4 of 197] Compiling Data.ByteString.Hash ( plutus-core/src/Data/ByteString/Hash.hs, dist/build/Data/ByteString/Hash.o, dist/build/Data/ByteString/Hash.dyn_o )
plutus-core-lib-plutus-core> [  5 of 197] Compiling Data.SatInt      ( plutus-core/src/Data/SatInt.hs, dist/build/Data/SatInt.o, dist/build/Data/SatInt.dyn_o )
plutus-core-lib-plutus-core> plutus-core/src/Data/SatInt.hs:214:29: error:
plutus-core-lib-plutus-core>     Variable not in scope: smallInteger :: Int# -> Integer
plutus-core-lib-plutus-core>     |
plutus-core-lib-plutus-core> 214 |     toInteger (SI (I# i)) = smallInteger i
plutus-core-lib-plutus-core>     |                             ^^^^^^^^^^^^
plutus-core-lib-plutus-core> [  6 of 197] Compiling ErrorCode        ( common/ErrorCode.hs, dist/build/ErrorCode.o, dist/build/ErrorCode.dyn_o )
```

Not sure how to fix this yet.

**Comment by srid** [comment]
HLS support is work in progress: https://github.com/haskell/haskell-language-server/pull/2503

**Comment by L-as** [comment]
[I](https://github.com/haskell-crypto/cryptonite/issues/357)

**Comment by L-as** [comment]
```
plutus-core-lib-plutus-core> plutus-core/src/Universe/Core.hs:770:10: error:
plutus-core-lib-plutus-core>     • Could not deduce (GEq uni)
plutus-core-lib-plutus-core>         arising from the superclasses of an instance declaration
plutus-core-lib-plutus-core>       from the context: Closed uni
plutus-core-lib-plutus-core>         bound by the instance declaration
plutus-core-lib-plutus-core>         at plutus-core/src/Universe/Core.hs:770:10-48
plutus-core-lib-plutus-core>     • In the instance declaration for ‘Hashable (SomeTypeIn uni)’
plutus-core-lib-plutus-core>     |
plutus-core-lib-plutus-core> 770 | instance Closed uni => Hashable (SomeTypeIn uni) where
plutus-core-lib-plutus-core>     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plutus-core-lib-plutus-core> plutus-core/src/Universe/Core.hs:773:10: error:
plutus-core-lib-plutus-core>     • Could not deduce: Everywhere uni Eq
plutus-core-lib-plutus-core>         arising from the superclasses of an instance declaration
plutus-core-lib-plutus-core>       from the context: (Closed uni, Everywhere uni Hashable)
plutus-core-lib-plutus-core>         bound by the instance declaration
plutus-core-lib-plutus-core>         at plutus-core/src/Universe/Core.hs:773:10-76
plutus-core-lib-plutus-core>     • In the instance declaration for ‘Hashable (ValueOf uni a)’
plutus-core-lib-plutus-core>     |
plutus-core-lib-plutus-core> 773 | instance (Closed uni, uni `Everywhere` Hashable) => Hashable (ValueOf uni a) where
plutus-core-lib-plutus-core>     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plutus-core-lib-plutus-core> plutus-core/src/Universe/Core.hs:773:10: error:
plutus-core-lib-plutus-core>     • Could not deduce (GEq uni)
plutus-core-lib-plutus-core>         arising from the superclasses of an instance declaration
plutus-core-lib-plutus-core>       from the context: (Closed uni, Everywhere uni Hashable)
plutus-core-lib-plutus-core>         bound by the instance declaration
plutus-core-lib-plutus-core>         at plutus-core/src/Universe/Core.hs:773:10-76
plutus-core-lib-plutus-core>     • In the instance declaration for ‘Hashable (ValueOf uni a)’
plutus-core-lib-plutus-core>     |
plutus-core-lib-plutus-core> 773 | instance (Closed uni, uni `Everywhere` Hashable) => Hashable (ValueOf uni a) where
plutus-core-lib-plutus-core>     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plutus-core-lib-plutus-core> plutus-core/src/Universe/Core.hs:777:10: error:
plutus-core-lib-plutus-core>     • Could not deduce: Everywhere uni Eq
plutus-core-lib-plutus-core>         arising from the superclasses of an instance declaration
plutus-core-lib-plutus-core>       from the context: (Closed uni, Everywhere uni Hashable)
plutus-core-lib-plutus-core>         bound by the instance declaration
plutus-core-lib-plutus-core>         at plutus-core/src/Universe/Core.hs:777:10-81
plutus-core-lib-plutus-core>     • In the instance declaration for ‘Hashable (Some (ValueOf uni))’
plutus-core-lib-plutus-core>     |
plutus-core-lib-plutus-core> 777 | instance (Closed uni, uni `Everywhere` Hashable) => Hashable (Some (ValueOf uni)) where
plutus-core-lib-plutus-core>     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plutus-core-lib-plutus-core> plutus-core/src/Universe/Core.hs:777:10: error:
plutus-core-lib-plutus-core>     • Could not deduce (GEq uni)
plutus-core-lib-plutus-core>         arising from the superclasses of an instance declaration
plutus-core-lib-plutus-core>       from the context: (Closed uni, Everywhere uni Hashable)
plutus-core-lib-plutus-core>         bound by the instance declaration
plutus-core-lib-plutus-core>         at plutus-core/src/Universe/Core.hs:777:10-81
plutus-core-lib-plutus-core>     • In the instance declaration for ‘Hashable (Some (ValueOf uni))’
plutus-core-lib-plutus-core>     |
plutus-core-lib-plutus-core> 777 | instance (Closed uni, uni `Everywhere` Hashable) => Hashable (Some (ValueOf uni)) where
plutus-core-lib-plutus-core>     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by L-as** [comment]
I merged this so we don't make more incompatible changes

**Pull request merged**
