### PR TITLE
Mario/records

### PR DESCRIPTION
**Pull request by blamario**
Added `instance PlutusType` and a couple more examples.

### CODE REVIEW

**Comment by L-as** [comment]
You should rebase ontop of staging

**Comment by blamario** [comment]
staging is still broken

**Comment by blamario** [comment]
By which I mean that tests fail after the `Tracing` test. However I've just restored the LetRec tests; the issue was the GHC upgrade, but only insofar the TH splices needed to be repositioned, nothing to do with kinds.

**Comment by L-as** [comment]
It shouldn't be broken?

**Comment by blamario** [comment]
My `cabal test` output on `staging` ends with

        PAsData equality:                                                      OK
        Tracing:                                                               OK
        examples: <stdout>: commitBuffer: invalid argument (invalid character)

**Comment by blamario** [comment]
Any idea what could this problem be? I have submitted PR #114 on top of staging and I can continue working there by disabling the tests that fail for me, but it would be nice to have a solid base to work on. I.e. either master or properly-behaved staging.

**Comment by blamario** [comment]
It's something to do with the locale, in that Greek letters break the test output, but I don't see why the same output works on master.

**Comment by blamario** [comment]
export LC_ALL=C.UTF-8
fixed the problem. The output didn't work under `en_CA.UTF-8` nor `en_US.UTF-8`, I guess Greek letters are incomprehensible in North America.

**Pull request closed without merging**
