### PR TITLE
Cleanup `Plutarch.Test.Property` (and export?)

### PR DESCRIPTION
**Pull request by srid**
This builds on top of the prior upstreaming in #357 to prepare the property testing library for use in other projects.

- Replace `Util.hs:EquivalenceMethod` with `Equality`/`Totality`, because the former can allow the library user to generate redundant tests.
- Replace `haskPlutEquiv` with `prop_haskEquiv`; the latter uses -
  - The new Equality/Totality types
  - TypeApplications instead of proxy helpers (thus avoids large exports)
  - `NP` from sop-core to build arguments.
- Move `Marshal` to separate module
- Remove unused generators

As well as some upstreaming:

- Use a large budget for evaluating property tests by necessity
- Upstream `prop_dataRoundTrip` in Extra module, which will contain properties based on `prop_haskEquiv`
- `Marshal`: add default implementation using `PLifted`

### CODE REVIEW

**Comment by L-as** [comment]
> This builds on top of the prior upstreaming in https://github.com/Plutonomicon/plutarch/pull/357 to prepare the property testing library for use in other projects.

This doesn't make sense when you consider that it's `plutarch-test` which is unusable by downstream projects. You could rename `plutarch-test` to `plutarch-internal-test` and make a new `plutarch-test` that doesn't depend on `sydtest`.

**Comment by L-as** [comment]
We could also remove the `sydtest` dependency from `plutarch-test`.

**Comment by L-as** [comment]
The third option is not to merge the code at all and remove all the unused property testing code.

**Comment by srid** [comment]
Ardana still can use it, though. 

I am assuming that other projects refrain from using `plutarch-test` because of sydtest licensing restrictions. That said, even though `Plutarch.Test.Property` can _currently_ only be used by Ardana, I expect it will _eventually_ become usable for other projects after #331 is done. 

I'd offer 2 more options:

- We can move this code to a separate package, `plutarch-test-property`, if other projects want to use it right away without waiting for #331, but this extra structure is not necessary and becomes redundant after tasty migration.
- Alternatively, we un-export `Plutarch.Test.Property`, remove the unused `Extra.hs` - and merge the PR. Ardana projects would patch the .cabal in Nix to export the module (until #331 is done that is).

**Comment by L-as** [comment]
I don't see why we would do something specific to Ardana.

**Comment by srid** [comment]
We don't have to -- hence that 2nd option.

**Comment by TotallyNotChase** [comment]
well, in any case, are we working on that sydtest switch? What would be some of the challenges/blockers you can foresee?

**Review by L-as — APPROVED** [review]
Merging as this is still a good change

**Comment by srid** [comment]
> well, in any case, are we working on that sydtest switch? What would be some of the challenges/blockers you can foresee?

I finally got to work on it. It probably will be hspec + hedgehog. Main question was about accessing test hierarchy in monadic specs (for determining golden file paths); and one approach to that (could be upstreamed) is: https://github.com/Plutonomicon/plutarch/commit/fd84c3d6bf6d3035aaec84aab5ea0ebea62d7a45

**Pull request merged**
