### PR TITLE
Add the Plutarch guide

### LINKED ISSUE #45: Documentation
We probably want the documentation to be in a `docs` directory in this repository.

I've assigned Chase as he is already working on this.

### PR DESCRIPTION
**Pull request by TotallyNotChase**
Closes #45 

This is ready to review. But I have marked it as a draft since I want to put in a bit more information. However, I think there will still be some unfilled sections.

### CODE REVIEW

**Review by L-as — CHANGES_REQUESTED** [review]
Can you make a directory for documentation?

**Comment by srid** [comment]
If we'd like to eventually have a generated docs site like https://input-output-hk.github.io/cardano-wallet/ - let me know I can help with that.

**Comment by L-as** [comment]
I'm thinking we should merge this for now and improve it later.

**Comment by L-as** [comment]
We should add a definition for unsafe functions. Unsafe functions are functions which can give you terms that are not in their type, e.g. `punsafeCoerce` can give you a `Term s PInteger` even though the underlying value could be a function in reality, which is unsafe, and unsound. Partial functions are not unsafe.

**Comment by TotallyNotChase** [comment]
@L-as I'll add a section for unsafe functions and get this ready by EOD. I just want to add in a "good" validator example using `ScriptContext`.

**Comment by TotallyNotChase** [comment]
Added some more information + fixes + more involved validator example. This is now merge-able.

**Review by L-as — APPROVED** [review]
LGTM

**Pull request merged**
