### PR TITLE
Fix missing imports during development mode

### PR DESCRIPTION
**Pull request by TotallyNotChase**
We need to have `cabal build -f development` in CI

### CODE REVIEW

**Comment by TotallyNotChase** [comment]
Hold on - there's a failing test. I'll fix that.

**Comment by TotallyNotChase** [comment]
Here's something subtle: Any function that uses tracing in its dependency chain (`ptraceError`, `ptrace` etc.), needs finer attention in the test suite if comparing script outputs directly. Of course, the `trace` builtin function call is only present in the script in development mode.

So the compiled script will be different in the two modes. Hence, when testing against compiled output - be careful of the difference.

**Comment by TotallyNotChase** [comment]
And having to use CPP in test files is a pain..... I wish backpack worked.

I'm having a hard time getting fourmolu to not die on a file with CPP

**Comment by TotallyNotChase** [comment]
Alright, that should work.

Sorry for butchering up your test file @blamario :(

**Review by L-as — APPROVED** [review]
LGTM

**Pull request merged**
