### PR TITLE
Bool instance

### PR DESCRIPTION
**Pull request by anton-k**
There is cool package `Boolean` which provides generic Booleans useful for EDSLs.
I thought maybe it can be useful for Plutarch.

### CODE REVIEW

**Review by MatthewCroughan — APPROVED** [review]

**Comment by TotallyNotChase** [comment]
I don't think this needs to be in the main Plutarch repo though. Perhaps it makes more sense to have it be a separate repository that people can add as a dependency if they need to.

**Comment by anton-k** [comment]
@TotallyNotChase  With those instances we get some nice functions that emulate guards and case-expressions. I think it can also be useful for plutarch.

**Comment by TotallyNotChase** [comment]
Ah, `guardB` and `caseB` look pretty cool. But I think those should just be regular, monomorphized Plutarch term utilities. Won't need the `boolean` dep or instances then.

**Comment by L-as** [comment]
`guardB` looks nice, but I don't think it's good to depend on an unmaintained dependency. Last update is almost 5 years ago.

**Comment by anton-k** [comment]
That's ok. I just saw that you use Num instances  and thought that you might be interested to rely on classes for booleans too.
Just to say couple of words in defense of that package. If something does not change every half a year does not mean that it's not useful. Num has not changed for about a 30 years. How often would you like the meaning of boolean operators or comparison operators to be changed?

**Comment by nixinator** [comment]
https://xkcd.com/2347/

**Comment by L-as** [comment]
I completely agree with that sentiment, however, GHC and base often have breaking changes.

**Comment by L-as** [comment]
If we are to have this in Plutarch we want to do this without adding the unnecessary dependency.

**Pull request closed without merging**
