### PR TITLE
Plutarch 1.1 guide

### LINKED ISSUE #200: Indicate knowledge prerequisites in GUIDE.md
It may be helpful for adoption of Plutarch to have a list of resources of both "required" and "helpful" prerequisites for comprehension. There are a number of terms that I've seen before, but do not fully understand; a younger me would be intimidated, chase down the semantics of those terms, and likely abandon learning plutarch as "too hard". The missing resources don't actually seem to affect my current comprehension, however, so I am assuming the actual prerequisites are light. But some readers get skiddish if unfamiliar terms are not either defined or explicitly noted as inconsequential, and in the interest of lowering the barrier to entry, here are some examples:

  - It _appears_ that familiarity with UPLC is assumed. The signature `eval :: ClosedTerm a -> Either ScriptError (ExBudget, [Text], Program DeBruijn DefaultUni DefaultFun ())` is the first type signature provided, and I (personally) don't know what the last element of the triple means, except that I am told it is the script result. This may look scary to newbies, and give the false impression that Plutarch is beyond them.
  - Similarly, the concept of "Lifts" is something that I've inferred while learning haskell, but I've never had adequately explained. If a concise resource exists, it could be helpful to link. This goes for the `ST` monad as well. The current guide gives the impression that these should be obvious.
  - Scott Encoding 
  - `DefaultUni` -- this is linked later in the document, but the link is broken (since the IOHK haddock instance never seems to work....)

If someone is able to give a basic run-down of intended audience and assumed level of expertise, I'd be happy to submit edits.

### LINKED ISSUE #218: Expand introduction to `pcon` in guide.
> Or from Plutarch terms within other constructors using `pcon` (requires [`PlutusType`/`PCon`](#plutustype-pcon-and-pmatch) instance)-
> 
> ```haskell
> import Plutarch.Prelude
> import Plutarch.Maybe (PMaybe (PJust))
> 
> -- | Create a plutarch level optional value from given value.
> f :: Term s (a :--> PMaybe a)
> f = plam $ \x -> pcon $ PJust x
> -- Note that 'PMaybe' has a 'PlutusType' instance.
> ```

I feel like this section of the guide could be expanded/re-written. Not by much but I don't believe the introduction to `pcon` is intuitive to those unfamiliar with Plutarch. 

I found looking up the type signature of `pcon` useful, and thereby came up with my own demonstration, which I included in my own notes:

```haskell
ghci> :t pconstant True
Term s PBool
ghci> :t PTrue
PBool s
ghci> :t pcon PTrue
Term s PBool
```

I don't know if it's the kind of thing you'd want to include but it is what made `pcon` "click" for me.

### LINKED ISSUE #219: Document GHC 9 specific features
I thought the monadix syntax was the only point of difference, but record field access is also impacted. Looks like we can use record dot preprocessor plugin in GHC 8.10.

### PR DESCRIPTION
**Pull request by TotallyNotChase**
A rework of the guide for Plutarch 1.1 changes and additions.

I aim to finish all the TODOs by the end of the day and add a few more sections so the users guide can essentially be "finished" as of Plutarch 1.1.

Closes #200 
Closes #218
Closes #219

### CODE REVIEW

**Comment by L-as** [comment]
Can you recommend the `cont` workaround for GHC 8.10 users?

**Comment by TotallyNotChase** [comment]
> Can you recommend the `cont` workaround for GHC 8.10 users?

Yeah, it should be [in there](https://github.com/Plutonomicon/plutarch/pull/222/files#diff-49cd8b759265ca93415f24f09658c92b903bc478b98426fa3841741f746fa772R363) already.

**Comment by TotallyNotChase** [comment]
This is basically done but I want to review the entire thing prior to merge.

**Comment by TotallyNotChase** [comment]
@L-as I added a section for briefly explaining data and scott encoding - it's probably worth reviewing independently.

**Review by L-as — APPROVED** [review]
LGTM

**Comment by L-as** [comment]
Maybe you want to make issues for the TODOs.

**Comment by TotallyNotChase** [comment]
> Maybe you want to make issues for the TODOs.

Yes, I'll add them as tasks on #105

**Comment by srid** [comment]
It is difficult to review these big diffs; may I suggest splitting `GUIDE.md` into smaller files?

**Comment by TotallyNotChase** [comment]
> It is difficult to review these big diffs; may I suggest splitting `GUIDE.md` into smaller files?

Definitely something I have in mind. Would be easier to organize things as well. I'll try to get to it soon.

**Pull request merged**
