### PR TITLE
plam: Make inference work for `id` function

### LINKED ISSUE #2: Improve type inference of plam
In definitions of data types, plam will often fail unless given an explicit type.

See https://github.com/Plutonomicon/plutarch/blob/master/Plutarch/Maybe.hs#L14

### PR DESCRIPTION
**Pull request by L-as**
Fixes #2

### CODE REVIEW

**Comment by TotallyNotChase** [comment]
This probably broke long ago and I missed it but the following doesn't work, even though it sure as hell worked before-
```hs
pf :: Term s (b :--> a :--> a)
pf = plam $ \_ y -> y
```
It gives
```
Overlapping instances for Plutarch.PLamN
  (b'2 -> b'2) (a :--> a) s
arising from a use of ‘plam’
```

**Comment by L-as** [comment]
This broke when we switched away from incoherent instances unfortunately.

**Comment by TotallyNotChase** [comment]
I see, somewhat concerning that neither of these work though-
```hs
pf :: Term s (b :--> a :--> a)
pf = plam $ \_ y -> y

pf' :: Term s (POpaque :--> a :--> a)
pf' = plam $ \(_ :: Term _ _) y -> y

pf'' :: Term s (b :--> a :--> a)
pf'' = plam $ flip const
```

**Comment by TotallyNotChase** [comment]
On the bright side, I did actually notice this improving type inference in quite a few places.

**Comment by L-as** [comment]
OK, so it's a step forward, even if it doesn't fix #2

**Pull request merged**
